name: Go
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    - name: Build
      run: go build -o app main.go  # Compila directamente el archivo main.go
    - name: Test
      run: go test -v ./...   # Ejecuta todas las pruebas en el repositorio
    - run: echo "🍏 This job's status is ${{ job.status }}."

